### PR TITLE
Add type hint

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Add type hint with PHPDoc comment annotation style.

### CODE REVIEW

**Comment by Jord-JD** [comment]
Thanks for this.

Before merging, I'll have to work out why the Travis tests on `hhvm` have started failing.

**Comment by peter279k** [comment]
Hi @DivineOmega, thank you for your reply and concern.

After digging the latest Travis CI build log, it's related to this [issue](https://github.com/facebook/hhvm/issues/8387). The error message output is as follows:

```
array_creation_expression is not allowed in write context
```

I think we have to two approaches for solving this issue:

- Fix the syntax and let this still support the `HHVM` test in Travis CI build.
- Drop the `hhvm` test in Travis CI build.

What do you think about that? Thanks.

BTW, the issue happens on `illuminate/support/Arr.php` class, the following syntax declaration doesn't allow in `hhvm` engine.

image

**Comment by Jord-JD** [comment]
Not certain. Since this has been caused by a change in the `illuminate/support` package, I'm inclined to say we just drop support for `hhvm`.

**Comment by peter279k** [comment]
@DivineOmega, after digging the previous Travis CI build logs, I found that the `illuminate/suuport` `^5.7` version will make the `hhvm` test failed.

In order to fix this, I let this package version defined in `composer.json`. It is as follows:

```
......
    "require": {
        "illuminate/support": ">=5.1 <5.7"
    },....
```

**Comment by Jord-JD** [comment]
@peter279k This would prevent the package working in Laravel 5.7. Instead of this, could you just remove `hhvm` from the Travis CI file?

**Comment by peter279k** [comment]
@DivineOmega , I agree with you because we want to support the `laravel-5.7` version.

I will remove `hhvm` test during Travis CI build.

**Comment by peter279k** [comment]
Now the latest [Travis CI build](https://travis-ci.org/DivineOmega/array_undot) is done :)

**Comment by Jord-JD** [comment]
@peter279k Thanks Peter. Could you also revert the change to the `illuminate/support` version constraint so Laravel 5.7 is supported?

**Comment by peter279k** [comment]
The `illuminate/support` version is reverted and it will support `5.7` version.

**Comment by Jord-JD** [comment]
Thanks! :+1:

**Pull request merged**
